export const types = {
  mutations: {
    SET_ALL_COUNTRIES: "SET_ALL_COUNTRIES",
    SET_GLOBAL_SUMMARY: "SET_GLOBAL_SUMMARY",
    SET_COUNTRY_SUMMARY: "SET_COUNTRY_SUMMARY",
    SET_MAP_CENTER: "SET_MAP_CENTER",
    SET_NEWS_COUNTRY: "SET_NEWS_COUNTRY",
    SET_COUNTRY_HISTORY: "SET_COUNTRY_HISTORY"
  },
  actions: {
    GET_ALL_COUNTRIES: "GET_ALL_COUNTRIES",
    GET_GLOBAL_SUMMARY: "GET_GLOBAL_SUMMARY",
    GET_COUNTRY_SUMMARY: "GET_COUNTRY_SUMMARY",
    CLEAR_COUNTRY_SUMMARY: "CLEAR_COUNTRY_SUMMARY",
    SET_MAP_CENTER: "SET_MAP_CENTER",
    GET_NEWS_COUNTRY: "GET_NEWS_COUNTRY",
    CLEAR_NEWS_COUNTRY: "CLEAR_NEWS_COUNTRY",
    GET_COUNTRY_HISTORY: "GET_COUNTRY_HISTORY"
  }
};
