export const types = {
  mutations: {
    SET_ALL_COUNTRIES: "SET_ALL_COUNTRIES",
    SET_GLOBAL_SUMMARY: "SET_GLOBAL_SUMMARY",
    SET_COUNTRY_SUMMARY: "SET_COUNTRY_SUMMARY",
    SET_MAP_CENTER: "SET_MAP_CENTER"
  },
  actions: {
    GET_ALL_COUNTRIES: "GET_ALL_COUNTRIES",
    GET_GLOBAL_SUMMARY: "GET_GLOBAL_SUMMARY",
    GET_COUNTRY_SUMMARY: "GET_COUNTRY_SUMMARY",
    CLEAR_COUNTRY_SUMMARY: "CLEAR_COUNTRY_SUMMARY",
    SET_MAP_CENTER: "SET_MAP_CENTER"
  }
};
